fos_user:
    db_driver:      orm
    firewall_name:  admin
    user_class:     App\Entity\User
    from_email:
        address: "tto@gmail.com"
        sender_name: "Tap To Order"
    group:
        group_class: FOS\UserBundle\Entity\Group

#
#    group:
#        group_class:   Sonata\UserBundle\Entity\BaseGroup
#        group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)
#
#    service:
#        user_manager: sonata.user.orm.user_manager