security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
#        FOS\UserBundle\Model\UserInterface:
#            algorithm: bcrypt

    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        users:
            entity:
                class: App\Entity\User
                property: username
        tags:
            entity:
                class: App\Entity\Tag
                property: idTag
#        fos_userbundle:
#            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: users
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: /admin/login
                check_path: /admin/login_check
                default_target_path: sonata_admin_dashboard
                use_forward: false
                failure_path: null
            logout:
                path: /admin/logout
                target: /admin/login
            anonymous: ~

        main:
            pattern: ^/
            provider: tags
            anonymous: ~
            logout: ~
            guard:
                authenticators:
                    - App\Security\IdTagAuthenticator

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    access_control:
        # Admin Backend
        - { path: ^/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }

        # Main Frontend
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }