sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    title:      Acme
    title_logo: bundles/app/images/fancy_acme_logo.png

services:
    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        public: true

    admin.subcategory:
        class: App\Admin\SubcategoryAdmin
        arguments: [~, App\Entity\Subcategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Subcategory" }
        public: true

    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Product" }
        public: true