sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_admin:
    title:      Acme
    title_logo: bundles/app/images/fancy_acme_logo.png

sonata_user:
    security_acl: false
    manager_type: orm

    table:
        user_group: "users_groups"

    class:
        user: 'App\Entity\User'
        group: 'App\Entity\Group'

services:
    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categories" }
        public: true

    admin.subcategory:
        class: App\Admin\SubcategoryAdmin
        arguments: [~, App\Entity\Subcategory, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Subcategories" }
        public: true

    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Products" }
        public: true

    admin.choice:
        class: App\Admin\ChoiceAdmin
        arguments: [~, App\Entity\Choice, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Choices" }
        public: true

    admin.allergen:
        class: App\Admin\AllergenAdmin
        arguments: [~, App\Entity\Allergen, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Allergens" }
        public: true

    admin.tag:
        class: App\Admin\TagAdmin
        arguments: [~, App\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Tags" }
        public: true

    admin.establishment:
            class: App\Admin\EstablishmentAdmin
            arguments: [~, App\Entity\Establishment, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Content", label: "Establishment" }
            public: true