#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

# Depends on sensio/framework-extra-bundle, doctrine/annotations, and doctrine/cache
#   install with composer req sensio/framework-extra-bundle annot
controllers:
    resource: ../src/Controller/
    type: annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

fos_user_security_login:
    path: /admin/login
    controller: fos_user.security.controller:loginAction
    methods: [GET, POST]

fos_user_security_check:
    path: /admin/login_check
    controller: fos_user.security.controller:checkAction
    methods: [POST]

fos_user_security_logout:
    path: /admin/logout
    controller: fos_user.security.controller:logoutAction
    methods: [GET, POST]